services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bike_rental_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Adomnikov3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bike_rental_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  django:
    build: .
    restart: always
    environment:
      POSTGRES_DB: bike_rental_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Adomnikov3
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    restart: always
    command: celery -A bike-rental-service worker -l info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  static_volume:
  media_volume: