version: '3.10.1'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: bike-rental-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Adomnikov3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    command: >
      sh -c   "redis-server"

  django:
    build: .\
    container_name: django
    restart: always
    environment:
      POSTGRES_DB: bike-rental-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Adomnikov3
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/static
    depends_on:
      - redis
      - db
    env_file:
      - .env
    command: >
      sh -c   "python manage.py makemigrations && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"


  celery:
    build: .
    restart: always
    container_name: celery
    command: celery -A bike-rental-service worker -l info -P gevent
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
