# Generated by Django 5.0.6 on 2024-07-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
