# Generated by Django 5.1.4 on 2024-12-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rental_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], max_length=10, null=True),
        ),
    ]
